//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterFallEntityProject.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblApproveSample
    {
        public int ApproveId { get; set; }
        public Nullable<int> SampleId { get; set; }
        public string SampleLocation { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> PassOrFail { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> TestResult { get; set; }
    }
}
