//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterFallEntityProject.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblActivity
    {
        public int ActivityId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> SampleId { get; set; }
        public string SampleLocation { get; set; }
        public string SampleType { get; set; }
        public Nullable<int> FrequencyDays { get; set; }
        public Nullable<int> FrequencyNumber { get; set; }
        public string ScheduleDate { get; set; }
        public string DeactivatedReason { get; set; }
        public Nullable<int> AcceptedReject { get; set; }
    }
}
