//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterFallEntityProject.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSchedule
    {
        public int ScheduleId { get; set; }
        public Nullable<int> SampleId { get; set; }
        public string SampleLocation { get; set; }
        public Nullable<int> FrequencyDays { get; set; }
        public Nullable<int> FrequencyNumber { get; set; }
        public string SampleType { get; set; }
        public string ScheduleDate { get; set; }
        public string CreatedBy { get; set; }
        public string createdDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string SampleName { get; set; }
    }
}
