//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterFallEntityProject.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTestGrouping
    {
        public int TestGroupId { get; set; }
        public string TestGroupName { get; set; }
        public string TestGroupDescription { get; set; }
        public string SelectedIds { get; set; }
        public string MappedSampleIdToTestGroup { get; set; }
        public string CreatedBy { get; set; }
        public string createdDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
    }
}
