//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterFallEntityProject.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblWorksheetEntry
    {
        public int WorksheetId { get; set; }
        public Nullable<int> SampleId { get; set; }
        public string SampleLocation { get; set; }
        public string SampleTime { get; set; }
        public string SampleType { get; set; }
        public string TestGroupName { get; set; }
        public string FinalResults { get; set; }
        public string Comments { get; set; }
    }
}
