//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterFallEntityProject.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WaterFallProjectEntities2 : DbContext
    {
        public WaterFallProjectEntities2()
            : base("name=WaterFallProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAdminChemicalTest> TblAdminChemicalTests { get; set; }
        public virtual DbSet<TblAdminIncubator> TblAdminIncubators { get; set; }
        public virtual DbSet<TblAdminMaster> TblAdminMasters { get; set; }
        public virtual DbSet<TblAdminSample> TblAdminSamples { get; set; }
        public virtual DbSet<TblTestGrouping> TblTestGroupings { get; set; }
        public virtual DbSet<TblSchedule> TblSchedules { get; set; }
        public virtual DbSet<TblApproveSample> TblApproveSamples { get; set; }
        public virtual DbSet<TblWorksheetEntry> TblWorksheetEntries { get; set; }
        public virtual DbSet<TblActivity> TblActivities { get; set; }
    }
}
